sudo: required
language: java
jdk:
- oraclejdk8
services:
- docker
addons:
  hosts:
  - docker
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
- docker save -o $HOME/docker_cache/docker.tar stfdigital-plataforma-ui $(docker history
  -q stfdigital-plataforma-ui | tail -n +2 | grep -v \<missing\> | tr '\n' ' ')
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - node_cache
  - node_modules
  - "$HOME/docker_cache"
before_install:
- ./shared/scripts/upgrade-docker.sh
- mkdir -p $HOME/docker_cache
install: docker load -i $HOME/docker_cache/docker.tar || true
script: ./gradlew docker && ./gradlew gulpTestUnit && ./shared/scripts/test-e2e.sh
after_success:
- ./gradlew gulpPublishUnitCoverage
- docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
- export REPO=supremotribunalfederal/stfdigital-plataforma-ui
- docker tag stfdigital-plataforma-ui $REPO:latest
- docker push $REPO:latest
notifications:
  slack:
    secure: cO2plplwVctvT9a5u4W1Xld3682p3TwSALDQrSdSncNMAhzykFSxUuy/QWg7G010oLNp6kHLDjNtWCSagYyqtXgpC7ECPD9TAivfBMeSYV1JvNvZ8toAIwhn+rq/OnpohmkZ4MAYvqseeyj8GQb18UBHANlErlO5rDbZ2K3jRpocJf5PiFydOMAquDp505TgiYDAFXoCQBQoEPy6CjNHyNOaKTl2AWdFCGmLdvXXyHo60TKquneiFblX/muqtdVH6cFfIjYPgfZErFHzBvsGrm/JiZXPvWwrJdFLzFgHbtZin84vP0fdHyAXCQHB3QaW2FeyC4x+/iD7NRE0hwo4OZyXjKPSWj+Jizsj7bGzgiIsb2P12Zloq5Vxe9afeaUSVD5gY5eReYDrYMqYJ8QKBVnHK/5FT3A9C4JDA9SAdKuJi/haceXKsgtCh6Z5bx3tIxii15y7rTCmx9cR+ylsvTBZ/4FJKuN4+4kabeQVyhcGPymxwnjz+VnyFZodacWQ+ZcGkw4HnDxmAdfAxRJPwq5st5US0jcoA/Jqy5Ih9oJEs8KA3TCcCnk8pXQ9KMotYr0YAlQoKJ/lTU4dHCdK9i2fsrpqDuRngdgxmYYNWeISaMPRuamUZkhy54Dj0Skf4s4jCBh0/9hHcDbU9rCjaCPxOX9ojqmqeq47omGg+oU=
env:
  global:
  - EUREKA_PREFER_IP_ADDRESS=false
  - RABBIT_OUT_NODE_PORT=5673
  - RABBIT_OUT_DIST_PORT=15673
  # DOCKER_EMAIL
  - secure: jlzGLw18cSkYdvmyrAsWxK4c2ekABAWLAjrM5wqzsVoF97Y7JmLj0z0gPo6ixniMsFjR+pgEUpdIW80y7VXwnhBBlarUyt8/eF6b2LtAwJOEphPovaNCYpioNIkqcOgjaDqZI1ttexzWikOu7lK0v1rjNiB9YFkTH1eLxSr+LdbYWkp01363M/qDKuFvSwMu7dRcYl3cknQAxquZ+EkOV14MEofDfHuHDye2vqqGS/cvIQstFKS7a09UrjCO41Zxaly12rKJLwpohBnwGy/HYWt1EvtWQRWIDpcBxxbBqkKh86E8LmPela373EgN5E3KAAXgSW/CRQhjMTp72dAqxKlvLjycRjVev2ODeXhMxr0SQcZnagn/+zJcI8VaGI/VDZAUFz1ZCNq8tczR2ROU8+mlhHdQMhCXDet2lGx7aQfmfSWXTp188KOIuAo/S8ft8HCVZ5Ci8SG1+pWlhVGvfYa2kRYlNI+xRCAEkU3dZLs2c0NMA40vOnw5c0bGBEgz51fcV2eg7iJaWsCpwmoUr2JBQdFvzIl4MN9TPRVlesMe9q/ZhMdYXxqLb5VHzzoP/A+a8sRIJ0/l9+xoIbgyO3dxNGIAsL1fs8t0EqhKmxEY6Wvn+Ax+2gUkSz2fGTyOERV5EoKYn3SqUy0qHymVAWvnXJBb5gNe511WZG2WTfQ=
  # DOCKER_USER
  - secure: oy6uV0/YXaQwqxbqSR6Vt9liOnzfjhDm/JnSq5acXMAmB/O3wmBOTI5McQVHzbUKeaER9rtP2liRMRhs5THLjNDWVfoaRWr1/JYxKpE6tw02TmLRArB3eu2LbG1i0brZOQ8LnrNZACWaOgDydzw523UyqDqkQc3ZdQMLHvOwe/mP0lhDA3ONwqwLJPtjviyKDWGTnMoxhjpBr1sigjB/W9d9D4JVEjxdElU3aHqekjwJ3a2/81YTp28Ol1AaOBM111VJ1xsDjbs63uUwFzoBgdruPNfel+jjYfzlcrapx/CWQh82J8onJ1Ioph2BVzFFl7HKLJH8BJGAe0g/8JzL4fMajnAAXd33YbeyS5uixlf4l5tD90AO5FGeKt6Cz6Bqt2+No4K4iu8FbuxC3ftE9WvkWeOTTQZlMyvDHtVJEEUztKqJPx1B/kSCNOJUPc/4qajeqFHBW3DD60No1qRYdxM1AkSiS8ZaqUpJldPVEWHqxQ+9be1f4srjLGOjCfq+vyqerrlHSO6YbpCpJZha4Dk6CZSh4eB9dAnyb0ufpjip5brs8KGLY49AFJ7JEqcC5ycCHieu4JfxaRaYaZNge5wEx5+EYRzeRzojCw835Vk74avQKQ7aRAoRlfh5rs5VFAoF3yYDt/37jQC66oLBrkaf5FQ/7IatOru9r+vkK4A=
  # DOCKER_PASS
  - secure: Rzp+dGQ1tFtprGVNWJi6KtVFFBmkYzjnM2PGaM5plNunIJ2dh3Y/zwVst7lv0FT4bwTSW1gxexoUNzd+TsFJoipgN+m5NhRyK1b3SWUlgiWwHFizOpD/kOkR00bNnDzZXaiyIMZUf99RbebkCTfBdIz1fU9o25h9O5fgakS3UIwWUQJLmRrrUYgxwEI4dbt4upYbBT4zjAd+4J45+G9/Ix41DKAKxyW4/PbGCujYnIQSsLxWreWAAtw4zspCL6U2VcbQMk1efPTg7WEgN2rJ9YZtdcWPrnhpiM4bYPn7srgoQL3MCR7zL9IezbK6QxbX+SBG/TvTfJRlsF2tfy91Jcy7w1msVCS9ZaSEpk+HX3Nci0xlpOGe49voDQY5JSt15cQ8sdgGQ0kIr2NCJ+n2XEcCWup0cMlHB/to9yiYNh+Qk5jEr/RjAK7ob6Pz76+kJlsCKb4iXbSf/04KDjj6lS1zc2cliLtLqwkoPiG+c7Dl6nxUGfchTnP+6OfiuYy03Jg4ppQ6UMQRMUECIqr51/yuQSOQPOirMFUuYeYO5hkVh0n1vJnMSpSrAfaufDGuDSyxC1YA+bU8CpiE2hZcKJjR9mMyUc9IouVgY8Kd6mcMst70CP+3zxnv+TC/ifb/Tr5L+wJLprYuC8dExjODVvwry8Fj4YKClmvpxzhQYdk=
  - COVERALLS_SERVICE_NAME=travis-ci
  # COVERALLS_REPO_TOKEN
  - secure: "niSycAVpWQTQvEhN2ySULJw+iUmTTaPbLF1BQVcguf/R09yYARsE7N4OTvna413OIVvZYoqOeGfuU7udkrU984CvnWyx/YF4glThdLJ2VT1qBCYcBs0WoulGIZNarFH4XxW8Znonmv0hvsvRqSuUtIfqeuazA0woIcJQ77yKCnQmDDawIv03tqcZN3qYZwCrAUVHeXkrcGKxZzPalF0T0Fslh3hw8MBzLsMyFYYrgrGYPWuV4r/RjW2cbPhnZH1RjpNtlkT0WceNNnJFHI2xnSZd/Yis0lKSHg+l4VTDjgapLZS6SW047dZDlIQAn7IFK6/L2L0Fsp5fAfI2xCMfUZinzop2aM+HBMIIGhL84QoYTLX8PposMIMmEs7sDHNkX55cYv/dq6bw5noQ1jrsH8V/vQicKMXH9lRc/O+IZKSxilMJxi6md+q8Jbo87UmVnm4upl9W1xOMXGIebMM9FU2Bc6dOJNAfY9YqDqTES4ykpPT9S9QLtEPpC9Z8IfAWlEth7gcnLKmMduMr1THB9+IANJ1Gm4C8UAhqcgv1FyrUswHwhfMD/OnDlDWG0PtuteV/veLefX5PDunu+sjgJ47/TZdZB0tXDePWtgU5FSuF2jZS8Hd+GhJ3WLgWgd7PxnIbmeXOVdaRwk41u0lj+SBaEYyb1Tz2UPYqY8+vDCg="
