# Define a configuração dos serviços para rodar localmente.
version: '2'
services:
  discovery:
    image: stfdigital-plataforma-discovery
    ports:
     - "8761:8761"
     - "47961:8000"
    environment:
     - JAVA_OPTS=${JAVA_DEBUG_OPTS} ${JAVA_SERVICE_OPTS}
  gateway:
    image: stfdigital-plataforma-gateway
    ports:
     - "8765:8765"
     - "47965:${JAVA_DEBUG_PORT}"
    environment:
     - JAVA_OPTS=${JAVA_DEBUG_OPTS} ${JAVA_SERVICE_OPTS}     
  userauthentication:
    image: stfdigital-plataforma-userauthentication
    ports:
     - "8095:8095"
     - "8195:8195"
     - "47995:${JAVA_DEBUG_PORT}"
    environment:
     - spring.profiles.active=${JAVA_SERVICE_SPRING_PROFILES}
     - JAVA_OPTS=${JAVA_DEBUG_OPTS} ${JAVA_SERVICE_OPTS}