# Define a configuração para rodar com imagens do Docker Hub
version: '2'
services:
  rabbit:
    extends:
      file: shared/compose/common.yml
      service: rabbit
  discovery:
    extends:
      file: shared/compose/common.yml
      service: discovery
  gateway:
    extends:
      file: shared/compose/common.yml
      service: gateway
    depends_on:
     - discovery
  services:
    extends:
      file: shared/compose/common.yml
      service: services
    depends_on:
     - rabbit
     - discovery
  userauthentication:
    extends:
      file: shared/compose/common.yml
      service: userauthentication
    depends_on:
     - rabbit
     - discovery
