version: '2'
services:
  discovery:
    container_name: discovery
    image: supremotribunalfederal/stfdigital-plataforma-discovery
  gateway:
    container_name: gateway
    image: supremotribunalfederal/stfdigital-plataforma-gateway
    depends_on:
     - discovery
  userauthentication:
    container_name: userauthentication
    image: supremotribunalfederal/stfdigital-plataforma-userauthentication
    depends_on:
     - discovery
