# Define a configuração para rodar com imagens locais
version: '2'
services:
  rabbit:
    extends:
      file: shared/compose/common.yml
      service: rabbit
  discovery:
    extends:
      file: shared/compose/common.yml
      service: discovery
    image: stfdigital-plataforma-discovery
  gateway:
    extends:
      file: shared/compose/common.yml
      service: gateway
    image: stfdigital-plataforma-gateway
    depends_on:
     - discovery
  services:
    extends:
      file: shared/compose/common.yml
      service: services
    image: stfdigital-plataforma-services
    depends_on:
     - rabbit
     - discovery
  userauthentication:
    extends:
      file: shared/compose/common.yml
      service: userauthentication
    image: stfdigital-plataforma-userauthentication
    depends_on:
     - rabbit
     - discovery
