# Define a configuração para rodar esse contexto construído localmente
version: '2'
services:
  gateway: # Ambassador apontando para o gateway rodando localmente
    container_name: gateway
    image: svendowideit/ambassador
    environment:
     - GATEWAY_PORT_8765_TCP=tcp://${HOST_ADDRESS}:8765