# Define a configuração para rodar esse contexto construído localmente
version: '2'
services:
  ui:
    extends:
      file: shared/compose/common.yml
      service: ui
    image: stfdigital-plataforma-ui
    depends_on:
     - gateway
