# Extende a configuração para rodar os testes e2e.
# Deve ser rodado em combinação com shared/compose/docker-compose.e2e.base.yml
version: '2'
services:
  ui:
    extends:
      file: shared/compose/common.yml
      service: ui
    image: stfdigital-plataforma-ui
    depends_on:
     - gateway
