# Define a configuração para ativar o mecanismo de logging
version: '2'
services:
  elk:
    extends:
      file: shared/compose/common.yml
      service: elk
    image: stfdigital-plataforma-logging-elk
  filebeat:
    extends:
      file: shared/compose/common.yml
      service: filebeat
    image: stfdigital-plataforma-logging-filebeat
    depends_on:
     - elk